experiment:
  env_type: caenv     # Environment Type
  env_metric: 1       # 1 for metric distances or 0 for non-metric
  Seed: 100           # Seed for reproducibility
  Runs: 10            # How many Runs per Tree
  Size: 20            # Nodes in Tree or Graph
  Initial_pos: "0-0 " # Initial Agent Node Position
  wr_l: 1             # Weight Lower Range in edges
  wr_u: 100           # Weight Upper Range in edges
  Env_Update: 4       # Environment Update Ticks