experiment:
  env_type: rndtree   # Environment Type
  Seed: 100           # Seed for reproducibility
  Runs: 10            # How many Runs per Tree
  Size: 23           # Nodes in Tree or Graph
  Initial_pos: 10     # Initial Agent Node Position
  Env_Update: 4       # Environment Update Ticks
